#!/usr/bin/env bash
_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export NATS_IMAGE=${NATS_IMAGE:="$(awk -F '[ :]' '{print $2}' "${_DIR}/Dockerfile")"}
export NATS_IMAGE_VERSION=${NATS_IMAGE_VERSION:="$(awk -F '[ :]' '{print $3}' "${_DIR}/Dockerfile")"}
export NATS_ROOT=${NATS_ROOT:="$DOKKU_LIB_ROOT/services/nats"}
export NATS_HOST_ROOT=${NATS_HOST_ROOT:=$NATS_ROOT}

export PLUGIN_UNIMPLEMENTED_SUBCOMMANDS=("backup" "backup-auth" "backup-deauth" "backup-schedule" "backup-schedule-cat" "backup-set-encryption" "backup-unschedule" "backup-unset-encryption" "clone" "connect" "export" "import")
export PLUGIN_COMMAND_PREFIX="nats"
export PLUGIN_CONFIG_ROOT=${PLUGIN_CONFIG_ROOT:="$DOKKU_LIB_ROOT/config/$PLUGIN_COMMAND_PREFIX"}
export PLUGIN_DATA_ROOT=$NATS_ROOT
export PLUGIN_DATA_HOST_ROOT=$NATS_HOST_ROOT
export PLUGIN_DATASTORE_PORTS=(4222)
export PLUGIN_DATASTORE_WAIT_PORT=4222
export PLUGIN_DEFAULT_ALIAS="NATS"
export PLUGIN_DISABLE_PULL=${NATS_DISABLE_PULL:=}
export PLUGIN_DISABLE_PULL_VARIABLE="NATS_DISABLE_PULL"
export PLUGIN_ALT_ALIAS="DOKKU_NATS"
export PLUGIN_IMAGE=$NATS_IMAGE
export PLUGIN_IMAGE_VERSION=$NATS_IMAGE_VERSION
export PLUGIN_SCHEME="nats"
export PLUGIN_SERVICE="Nats"
export PLUGIN_VARIABLE="NATS"
export PLUGIN_BASE_PATH="$PLUGIN_PATH"
export PLUGIN_CONFIG_SUFFIX="config"
if [[ -n $DOKKU_API_VERSION ]]; then
  export PLUGIN_BASE_PATH="$PLUGIN_ENABLED_PATH"
fi

export PLUGIN_BUSYBOX_IMAGE="busybox:1.31.1-uclibc"
export PLUGIN_AMBASSADOR_IMAGE="dokku/ambassador:0.3.3"
export PLUGIN_S3BACKUP_IMAGE="dokku/s3backup:0.10.3"
export PLUGIN_WAIT_IMAGE="dokku/wait:0.4.3"
